language: scala
scala:
  - 2.11.11
  - 2.12.3
jdk:
  - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION compile "testOnly com.github.karasiq.proxy.tests.rfc.* com.github.karasiq.proxy.tests.server.*"
sudo: false
